version: "3.3"

services:

  web:
    build:
      context: ./
      dockerfile: dockerfile
    container_name: web-node12
    image: web:node12
    ports:
      - '3000:3000'
    volumes:
       - ./:/usr/src/app


       